// Next
import Head from 'next/head';

// MUI
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Typography variant="h1" align="center" sx={{ fontSize: '2.2rem', marginBottom: '1.5rem' }}>
            Search Movies
          </Typography>
        </Container>
      </main>
    </>
  );
}
